config/routes.rb
Rails.application.routes.draw do
  resources :seats
  resources :venues
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/seat.rb
class Seat < ApplicationRecord

  def self.from_string(str)
    new(row: str[0], column: str[1..].to_i, status: "AVAILABLE")
  end

  def ==(other)
    other.is_a?(Seat) && row == other.row && column == other.column
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  KEY = [*'a'..'z']
  def distances
        @distances ||= Array.new(rows) do |i|
      Array.new(columns) do |j|
        i + (j - (columns / 2.0).floor).abs
      end
    end
  end

  def seat_distance(seat)
    distances[KEY.index(seat.row)][seat.column.pred]
  end

  def best_seat(available, k)
    available.chunk_while { |prev, subs| prev.row == subs.row && prev.column.succ == subs.column }
      .reject { |chunk| chunk.size < k }
      .each_with_object({}) {|chunk, memo| chunk.each_cons(k).each {|s| memo[s] = s.sum(&method(:seat_distance)) }}
      .min_by { |_, v| v }
      .first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: %i[ show edit update destroy ]

  # GET /seats or /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1 or /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats or /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: "Seat was successfully created." }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1 or /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: "Seat was successfully updated." }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1 or /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url, notice: "Seat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seat_params
      params.require(:seat).permit(:row, :column, :status)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[ show edit update destroy ]

  # GET /venues or /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1 or /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues or /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: "Venue was successfully created." }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1 or /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: "Venue was successfully updated." }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1 or /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: "Venue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venue_params
      params.require(:venue).permit(:rows, :columns)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ordway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seats/_form.html.erb
<%= form_with(model: seat) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
        <% seat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :row %>
    <%= form.text_field :row %>
  </div>

  <div class="field">
    <%= form.label :column %>
    <%= form.number_field :column %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th>Row</th>
      <th>Column</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <td><%= seat.row %></td>
        <td><%= seat.column %></td>
        <td><%= seat.status %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Row:</strong>
  <%= @seat.row %>
</p>

<p>
  <strong>Column:</strong>
  <%= @seat.column %>
</p>

<p>
  <strong>Status:</strong>
  <%= @seat.status %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>

app/views/venues/_form.html.erb
<%= form_with(model: venue) do |form| %>
  <% if venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
        <% venue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rows %>
    <%= form.number_field :rows %>
  </div>

  <div class="field">
    <%= form.label :columns %>
    <%= form.number_field :columns %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Venues</h1>

<table>
  <thead>
    <tr>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.rows %></td>
        <td><%= venue.columns %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rows:</strong>
  <%= @venue.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @venue.columns %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>